project:
  type: book
  output-dir: docs

book:
  title: "Flight Test Brevity"
  subtitle: "A Communications Guide"
  author: "Nathan Cook"
  date: 2023-06-02
  date-format: iso
  cover-image: /images/cover.png
  repo-url: https://github.com/cooknl/flight-test-brevity
  repo-actions: [issue]
  chapters:
    - index.qmd
    - intro.qmd
    - principles.qmd
    - references.qmd
  appendices: 
    - flight-test-brevity-codes-sections.qmd
    - multiservice-codes-applicable-to-flight-test.qmd
    - unsafe-comm.qmd
    - test-run.qmd
    - comm-plan.qmd

bibliography: zotero.json

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 2
  pdf:
    documentclass: scrreport
    lof: true
    lot: true
    toc-depth: 2

license: "CC BY-SA"
