project:
  type: book
  output-dir: docs

book:
  title: "Flight Test Brevity"
  author: "Nathan Cook"
  date: "2/2/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - principles.qmd
    - comm_plan.qmd
  appendices: 
    - multiservice-codes-applicable-to-flight-test.qmd
    - flight-test-brevity-codes.qmd

bibliography: zotero.json

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 2
  pdf:
    documentclass: scrreprt

license: CC BY-SA 4.0



